[features]
seeds = false
skip-lint = false
[programs.localnet]
burry_oracle_program = "3yU8tgZeBoaTfcqReY6LeDQcekMAnQ1DiwKvmxKPUncb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ixmorrow/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
